# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Starter' do
  use_frameworks!
  pod 'Modernistik', :path => '../../'

end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|

            # config.build_settings['SWIFT_VERSION'] = '4.0'
            if config.name == 'Release'
                config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
            else
                config.build_settings['SWIFT_COMPILATION_MODE'] = 'none'
            end

            if config.name == 'Debug'
                config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
            end

        end
    end
end
